config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "static_pages#index"

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'

  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  resources :users, only: [:new, :create, :edit, :update] do
    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :sessions, only: [:new, :create]
  resources :posts do
    resources :comments, only: [:create]
  end


end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
        
        
        def new
        end
        
        def create
                if params[:email].empty?
                        flash[:danger]=t('flash.passwordreset.create.error')
                        redirect_to password_reset_path
                else
                        @user=User.find_by(email: params[:email])
                        if @user.present?
                                PasswordMailer.with(user: @user).reset.deliver_now
                        end
                        
                        flash[:success]=t('flash.passwordreset.create.success')
                        redirect_to root_path
                end
        end

        def edit
                @user = User.find_signed(params[:token], purpose: "password_reset")
        rescue ActiveSupport::MessageVerifier::InvalidSignature
                flash[:danger]=t('flash.passwordreset.token')
                redirect_to entrar_path
        end
        
        def update
                @user = User.find_signed(params[:token], purpose: "password_reset")
                if @user.update(password_params)
                        flash[:success]=t('flash.passwordreset.update.success')
                        redirect_to entrar_path
                else
                        flash[:danger]=t('flash.passwordreset.update.error')
                        render :edit
                end
                rescue ActiveSupport::MessageVerifier::InvalidSignature
                        redirect_to entrar_path, danger: t('flash.passwordreset.token')
        end
        
        private
        def password_params
            params.require(:user).permit(:password, :password_confirmation)
        end

end

app/views/password_resets/edit.html.erb
<%= form_for @user, url: password_reset_edit_path(token: params[:token]) do |f| %>
    <% if flash[:danger] %>
        <div class="alert alert-danger">
            <%= flash[:danger] %>
        </div>
    <% elsif flash[:success] %>
        <div class="alert alert-success">
            <%= flash[:success] %>
        </div>
    <% end %>
  <div class="form-group mb-3">
    <%= f.label :password, 'Senha', class: 'form-label' %>
    <%= f.password_field :password, placeholder: 'Senha', class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :password_confirmation, 'Confirmação de Senha', class: 'form-label' %>
    <%= f.password_field :password_confirmation, placeholder: 'Confirmação de senha', class: 'form-control' %>
  </div>
  <div class="d-flex justify-content-between">
    <%= f.submit 'Editar', class: 'btn btn-primary' %>
    <%= link_to 'Voltar', root_url, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<div class="row">
    <strong>
        <h1 class="display-4 text-center">Esqueceu a sua senha ?</h1>
    </strong>
    
    <%= form_with url: password_reset_path do |f| %>
        <div class="mb-3">
            <%= f.label :email, class: 'form-label' %>
            <%= f.email_field :email, class: 'form-control' , placeholder: "jose@gmail.com" %>
        </div>
        <div class="mb-3 d-flex justify-content-between">
            <%= f.submit 'Enviar', class: 'btn btn-primary' %>
        </div>
    <% end %>
</div>