config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "static_pages#index"

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'

  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  resources :users, only: [:new, :create, :edit, :update] do
    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :sessions, only: [:new, :create]
  resources :posts do
    resources :comments, only: [:create]
  end


end

app/models/user.rb
class User < ApplicationRecord
    has_many :post, dependent: :destroy
    has_many :comments, dependent: :destroy
    
    has_secure_password


    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    
    validates :name, presence: true, length: {maximum: 50}
    validates :password, length: {minimum: 6}
    validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: true }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_in_user, only: [:edit, :update, :edit_password, :update_password]

    def new
        @user= User.new
    end

    def create 
        @user= User.new(user_params)
        if @user.save
            flash[:success]=t('flash.users.profile.create.success')
            redirect_to entrar_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        parametros=user_params.slice(:password, :password_confirmation)
        @user=current_user
        if !@user.authenticate(parametros[:password])
            flash[:danger]=t('flash.users.profile.update.error')
            redirect_to edit_user_path(current_user)
        else
            if @user.update(user_params)
                flash[:success]=t('flash.users.profile.update.success')
                redirect_to root_url
            else
                render 'edit'
            end
        end
    end

    def edit_password
    end

    def update_password
        parametros=password_params.slice(:password, :password_confirmation)
        @user=current_user
        if !@user.authenticate(password_params[:current_password])
            flash[:danger]=t('flash.users.password.update.error')
            redirect_to edit_password_user_path(current_user)
        else
            if current_user.update(parametros)
                flash[:success]=('flash.users.password.update.success')
                redirect_to root_url
            else
                render 'edit_password'
            end
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :current_password, :password, :password_confirmation)
    end

    def password_params
        Rails.logger.debug "Parâmetros recebidos: #{params.inspect}"
        params.require(:user).permit(:current_password, :password, :password_confirmation)
    end
end

app/views/users/_fields.html.erb
<%= render 'layouts/error_messages', object: f.object %>

<div class="mb-3">
  <%= f.label :name, 'Nome', class: 'form-label' %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="mb-3">
  <%= f.label :email,'Email', class: 'form-label' %>
  <%= f.email_field :email, class: 'form-control' %>
</div>

<div class="mb-3">
  <%= f.label :password, 'Senha', class: 'form-label' %>
  <%= f.password_field :password, class: 'form-control' %>
</div>

<div class="mb-3">
  <%= f.label :password_confirmation, 'Confirmação de Senha', class: 'form-label' %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

app/views/users/edit.html.erb
<div class="row mt-4">
    <div class="col-12 text-center mb-3">
      <h1>Editar Dados</h1>
      <p style="color: gray;">Edite seu Nome ou Email</p>
    </div>
  
    <div class="col-md-6 offset-md-3 col-xs-12">
      <%= form_for current_user do |f| %>
       <%= render 'fields', f: f %>   

       <div class="mb-3 d-flex justify-content-between">
        <%= f.submit 'Editar', class: 'btn btn-primary' %>
        <%= link_to 'Voltar',root_url, class: 'btn btn-secondary' %>
       </div>
      <% end %>
    </div>
</div>

app/views/users/edit_password.html.erb
<div class="row mt-4">
    <div class="col-12 text-center mb-3">
      <h1>Alterar Senha</h1>
    </div>
  
    <div class="col-md-6 offset-md-3 col-xs-12">
      <%= form_for current_user, url: update_password_user_path(current_user), method: :patch do |f|%>
      <%= render 'layouts/error_messages', object: f.object %>
      <div class="mb-3">
        <%= f.label :current_password, "Senha Atual" %>
        <%= f.password_field :current_password, class: "form-control" %>
      </div>
    
      <div class="mb-3">
        <%= f.label :password, "Nova Senha" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
    
      <div class="mb-3">
        <%= f.label :password_confirmation, "Confirme a Nova Senha" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    
      <%= f.submit "Atualizar Senha", class: "btn btn-primary" %>
      <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-12">
    <h1 class="text-center">Cadastre-se</h1>
  </div>

  <div class="col-md-6 offset-md-3 col-12">
    <%= form_for @user, data: { turbo: false }, class: "needs-validation" do |f| %>
      <%= render 'fields', f: f %>

      <div class="mb-3 d-flex justify-content-between">
        <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>
        <%= link_to 'Voltar', root_url, class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>