config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "static_pages#index"

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'

  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  resources :users, only: [:new, :create, :edit, :update] do
    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :sessions, only: [:new, :create]
  resources :posts do
    resources :comments, only: [:create]
  end


end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <strong>Ops!</strong> Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>:
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
 

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to 'Blogify', root_url, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#expanded-menu" aria-controls="expanded-menu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <!-- Conteúdo exibido em telas maiores e escondido em telas menores -->
      <div class="collapse navbar-collapse" id="expanded-menu">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if !user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'Faça um post', entrar_path, class: 'nav-link' %>
          </li>
          <% else %>
          <li class="nav-item active">
            <%= link_to 'Faça um post', new_post_path, class: 'nav-link' %>
          </li>
          <% end %>
        </ul>
        
        <ul class="navbar-nav ms-auto">
          <% if !user_signed_in? %>
            <li class="nav-item active">
              <%= link_to 'Nova Conta', new_user_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Entrar', entrar_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Bem-vindo, <%= current_user.name %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to 'Ver Posts', posts_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'Editar Dados', edit_user_path(current_user), class: 'dropdown-item' %></li>
                <li><%= link_to 'Editar Senha', edit_password_user_path(current_user), class: 'dropdown-item' %></li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <%= form_with url: sair_path, method: :delete, class: 'inline' do %>
                    <%= submit_tag 'Sair', class: 'dropdown-item' %>
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <head>
      <title>Blog</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      
      
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  
  
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  
     
      <%= javascript_importmap_tags %>
      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ...></script>
      <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true , type: "module" %>
  </head>
  

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="flash-container" style="height: 60px; padding: 10px;">
          <% flash.each do |key, message| %>
            <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
              <%= message %>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          <% end %>
        </div>      
        <%= yield %>
      </div>
  </body>  
</html>